export type NotificationPermissionState = 'unsupported' | 'denied' | 'granted' | 'default';

function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export function isPushSupported(): boolean {
  return (
    typeof window !== 'undefined' &&
    'serviceWorker' in navigator &&
    'PushManager' in window &&
    'Notification' in window
  );
}

export function getNotificationPermissionState(): NotificationPermissionState {
  if (!isPushSupported()) {
    return 'unsupported';
  }
  return Notification.permission as NotificationPermissionState;
}

export async function registerServiceWorker(): Promise<ServiceWorkerRegistration | null> {
  if (!isPushSupported()) return null;

  try {
    const registration = await navigator.serviceWorker.register('/sw.js', {
      scope: '/',
    });
    await navigator.serviceWorker.ready;
    return registration;
  } catch (error) {
    console.error('Service worker registration failed:', error);
    return null;
  }
}

export async function subscribeToPushNotifications(): Promise<{
  success: boolean;
  message?: string;
}> {
  if (!isPushSupported()) {
    return { success: false, message: 'Web Push is not supported on this browser.' };
  }

  const publicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
  if (!publicKey) {
    return {
      success: false,
      message: 'VAPID Public Key is missing in client environment.',
    };
  }

  try {
    const permission = await Notification.requestPermission();
    if (permission !== 'granted') {
      return {
        success: false,
        message: 'Notification permission was denied. Please allow notifications in your browser settings.',
      };
    }

    const registration = await registerServiceWorker();
    if (!registration) {
      return { success: false, message: 'Failed to register service worker.' };
    }

    const convertedVapidKey = urlBase64ToUint8Array(publicKey);
    const subscription = await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: convertedVapidKey as unknown as BufferSource,
    });

    const jsonSub = subscription.toJSON();
    const endpoint = jsonSub.endpoint;
    const p256dh = jsonSub.keys?.p256dh;
    const auth = jsonSub.keys?.auth;

    if (!endpoint || !p256dh || !auth) {
      return { success: false, message: 'Invalid subscription payload generated by browser.' };
    }

    // Send subscription to backend API
    const response = await fetch('/api/notifications/subscribe', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        endpoint,
        p256dh,
        auth,
        userAgent: navigator.userAgent,
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      return {
        success: false,
        message: errorData.error || 'Failed to save subscription on server.',
      };
    }

    return { success: true };
  } catch (error: any) {
    console.error('Push notification subscription error:', error);
    return {
      success: false,
      message: error?.message || 'Failed to subscribe to push notifications.',
    };
  }
}

export async function unsubscribeFromPushNotifications(): Promise<{
  success: boolean;
  message?: string;
}> {
  if (!isPushSupported()) {
    return { success: false, message: 'Web Push is not supported.' };
  }

  try {
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.getSubscription();

    if (subscription) {
      const jsonSub = subscription.toJSON();
      const endpoint = jsonSub.endpoint;

      // Revoke on server
      if (endpoint) {
        await fetch('/api/notifications/subscribe', {
          method: 'DELETE',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ endpoint }),
        }).catch(() => null);
      }

      await subscription.unsubscribe();
    }

    return { success: true };
  } catch (error: any) {
    console.error('Error unsubscribing from push:', error);
    return { success: false, message: error?.message || 'Failed to unsubscribe.' };
  }
}
